devices {
  name : "Fan"
  used_nodes : 2
  ctor_ts {impacts {impact_env : "dtemperature" impact_rate : -0.02}}
}
devices {
  name : "AirPurifier"
  used_nodes : 2
  ctor_ts {impacts {impact_env : "dpm_2_5" impact_rate : -0.8}}
}
devices {
  name : "Light"
  used_nodes : 2
  ctor_ts {impacts {}}
}
devices {
  name : "Camera"
  used_nodes : 2
  ctor_ts {impacts {}}
}
devices {
  name : "Humidifier"
  used_nodes : 2
  ctor_ts {
    impacts {impact_env : "dhumidity" impact_rate : +0.1}
    impacts {impact_env : "dpm_2_5" impact_rate : +0.6}
  }
}
devices {
  name : "Door"
  used_nodes : 2
  ctor_ts {use_open_close : true}
}
devices {
  name : "Curtain"
  used_nodes : 2
  ctor_ts {use_open_close : true}
}
devices {
  name : "Window"
  used_nodes : 2
  ctor_ts {use_open_close : true}
}
devices {
  name : "AirConditioner"
  used_nodes : 3
  ctor_ac {impact_rate : 0.05}
}
devices {
  name : "SMS"
  used_nodes : 2
  ctor_sms {}
}
